# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: csvrun
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
- env:
    - CGO_ENABLED=0
  goarch:
    - 386
    - amd64
    - arm
    - arm64
  goarm:
    - 6
    - 7
  goos:
    - darwin
    - freebsd
    - linux
    - netbsd
    - openbsd
    - windows
  ignore:
    - goos: darwin
      goarch: 386
  ldflags:
    - -s -w
  main: ./cmd/csvrun/csvrun.go
archives:
  - files:
      - CHANGELOG.md
      - LICENSE
      - README.md
    format_overrides:
      - goos: windows
        format: zip
    replacements:
      386: i386
      amd64: x86_64
      darwin: macos
      # darwin: macOS
      # freebsd: FreeBSD
      # linux: Linux
      # netbsd: NetBSD
      # openbsd: OpenBSD
      # windows: Windows
    wrap_in_directory: true
nfpms:
  - formats:
      - deb
      - rpm
    # ID of the nfpm config, must be unique.
    # Defaults to "default".
    id: csvrun
    homepage: "https://github.com/runeimp/csvrun"
    license: MIT
    replacements:
      386: i386
      amd64: x86_64
      darwin: macos
checksum:
  name_template: 'checksums.txt'
# signs:
#   - artifacts: checksum
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
